#' Generate standalone MCMC light-export helper code
#'
#' Returns the self-contained R code inserted into downloaded MCMC scripts.
#' The generated code includes safe within-chain downsampling and a fallback
#' posterior-draw summary with R-hat/ESS when CmdStan summary extraction fails.
#'
#' @return A character string containing R helper-function definitions.
#' @export
mcmc_light_export_helper_code <- function() {
paste0(
    "# \u2500\u2500 Helper: lightweight MCMC diagnostic export \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n",
    "# This object is designed for upload to HarmonizeR. It keeps only what the\n",
    "# Bayesian MCMC Diag and Post-Harmonization tabs need, while excluding the\n",
    "# full CmdStan fit and full MultiComBat result objects.\n",
    "#\n",
    "# Design:\n",
    "#   1. Extract selected posterior draws first.\n",
    "#   2. Downsample evenly within chain, not globally.\n",
    "#   3. Try fit_obj$summary(variables = keep_vars).\n",
    "#   4. If summary extraction fails, fall back to posterior_draws-based summary\n",
    "#      with R-hat / ESS computed by posterior::summarise_draws().\n",
    "\n",
    "`%||%` <- function(a, b) if (!is.null(a)) a else b\n",
    "\n",
    "safe_downsample_draws_by_chain <- function(draws_df, max_draws = 2000, seed = 1) {\n",
    "  if (is.null(draws_df)) return(NULL)\n",
    "\n",
    "  draws_df <- as.data.frame(draws_df, check.names = FALSE)\n",
    "\n",
    "  if (!all(c(\".chain\", \".iteration\") %in% names(draws_df))) {\n",
    "    warning(\"No .chain/.iteration columns found; using global downsampling only.\")\n",
    "    if (nrow(draws_df) > max_draws) {\n",
    "      set.seed(seed)\n",
    "      keep_rows <- sort(sample(seq_len(nrow(draws_df)), max_draws))\n",
    "      draws_df <- draws_df[keep_rows, , drop = FALSE]\n",
    "    }\n",
    "    return(draws_df)\n",
    "  }\n",
    "\n",
    "  draws_df$.chain <- as.integer(draws_df$.chain)\n",
    "  chains <- sort(unique(draws_df$.chain))\n",
    "  draws_per_chain <- max(1L, floor(max_draws / length(chains)))\n",
    "\n",
    "  out <- do.call(\n",
    "    rbind,\n",
    "    lapply(chains, function(ch) {\n",
    "      d <- draws_df[draws_df$.chain == ch, , drop = FALSE]\n",
    "      d <- d[order(d$.iteration), , drop = FALSE]\n",
    "\n",
    "      if (nrow(d) > draws_per_chain) {\n",
    "        set.seed(seed + as.integer(ch))\n",
    "        keep <- sort(sample(seq_len(nrow(d)), draws_per_chain))\n",
    "        d <- d[keep, , drop = FALSE]\n",
    "      }\n",
    "\n",
    "      d\n",
    "    })\n",
    "  )\n",
    "\n",
    "  rownames(out) <- NULL\n",
    "  out\n",
    "}\n",
    "\n",
    "summarize_draws_with_rhat_safe <- function(draws_df, chunk_size = 500) {\n",
    "  if (is.null(draws_df)) return(NULL)\n",
    "\n",
    "  draws_df <- as.data.frame(draws_df, check.names = FALSE)\n",
    "\n",
    "  meta_cols <- intersect(c(\".chain\", \".iteration\", \".draw\"), names(draws_df))\n",
    "  param_cols <- setdiff(names(draws_df), meta_cols)\n",
    "\n",
    "  if (length(param_cols) == 0) return(NULL)\n",
    "\n",
    "  has_chain_info <- all(c(\".chain\", \".iteration\") %in% names(draws_df))\n",
    "\n",
    "  if (has_chain_info) {\n",
    "    draws_df$.chain <- as.integer(draws_df$.chain)\n",
    "    chain_counts <- table(draws_df$.chain)\n",
    "    min_n <- min(chain_counts)\n",
    "\n",
    "    message(\"Draws per chain available for light summary:\")\n",
    "    print(chain_counts)\n",
    "    message(\"Using \", min_n, \" draws per chain for R-hat/ESS.\")\n",
    "\n",
    "    draws_balanced <- do.call(\n",
    "      rbind,\n",
    "      lapply(split(draws_df, draws_df$.chain), function(d) {\n",
    "        d <- d[order(d$.iteration), , drop = FALSE]\n",
    "        d[seq_len(min_n), , drop = FALSE]\n",
    "      })\n",
    "    )\n",
    "    rownames(draws_balanced) <- NULL\n",
    "  } else {\n",
    "    draws_balanced <- draws_df\n",
    "  }\n",
    "\n",
    "  message(\"Computing lightweight posterior summaries...\")\n",
    "\n",
    "  basic_summary <- lapply(param_cols, function(v) {\n",
    "    x <- draws_balanced[[v]]\n",
    "    x <- x[is.finite(x)]\n",
    "\n",
    "    if (length(x) == 0) {\n",
    "      return(data.frame(\n",
    "        variable = v,\n",
    "        mean = NA_real_,\n",
    "        median = NA_real_,\n",
    "        sd = NA_real_,\n",
    "        q5 = NA_real_,\n",
    "        q95 = NA_real_,\n",
    "        q025 = NA_real_,\n",
    "        q975 = NA_real_,\n",
    "        stringsAsFactors = FALSE\n",
    "      ))\n",
    "    }\n",
    "\n",
    "    data.frame(\n",
    "      variable = v,\n",
    "      mean = mean(x, na.rm = TRUE),\n",
    "      median = stats::median(x, na.rm = TRUE),\n",
    "      sd = stats::sd(x, na.rm = TRUE),\n",
    "      q5 = unname(stats::quantile(x, 0.05, na.rm = TRUE)),\n",
    "      q95 = unname(stats::quantile(x, 0.95, na.rm = TRUE)),\n",
    "      q025 = unname(stats::quantile(x, 0.025, na.rm = TRUE)),\n",
    "      q975 = unname(stats::quantile(x, 0.975, na.rm = TRUE)),\n",
    "      stringsAsFactors = FALSE\n",
    "    )\n",
    "  })\n",
    "\n",
    "  smry_basic <- do.call(rbind, basic_summary)\n",
    "\n",
    "  smry_basic$rhat <- NA_real_\n",
    "  smry_basic$ess_bulk <- NA_real_\n",
    "  smry_basic$ess_tail <- NA_real_\n",
    "\n",
    "  if (!has_chain_info) {\n",
    "    warning(\"No .chain/.iteration columns found; R-hat and ESS set to NA.\")\n",
    "    return(smry_basic)\n",
    "  }\n",
    "\n",
    "  if (!requireNamespace(\"posterior\", quietly = TRUE)) {\n",
    "    warning(\"Package posterior is not installed; R-hat and ESS set to NA.\")\n",
    "    return(smry_basic)\n",
    "  }\n",
    "\n",
    "  message(\"Computing R-hat/ESS from selected posterior draws in chunks...\")\n",
    "\n",
    "  chunks <- split(param_cols, ceiling(seq_along(param_cols) / chunk_size))\n",
    "  diag_list <- vector(\"list\", length(chunks))\n",
    "\n",
    "  for (k in seq_along(chunks)) {\n",
    "    vars_k <- chunks[[k]]\n",
    "    message(\"  R-hat/ESS chunk \", k, \" of \", length(chunks),\n",
    "            \" | variables: \", length(vars_k))\n",
    "\n",
    "    d_k <- draws_balanced[, c(\".chain\", \".iteration\", vars_k), drop = FALSE]\n",
    "    arr_k <- posterior::as_draws_array(d_k)\n",
    "\n",
    "    diag_k <- posterior::summarise_draws(\n",
    "      arr_k,\n",
    "      rhat = posterior::rhat,\n",
    "      ess_bulk = posterior::ess_bulk,\n",
    "      ess_tail = posterior::ess_tail\n",
    "    )\n",
    "\n",
    "    diag_k <- as.data.frame(diag_k, check.names = FALSE)\n",
    "\n",
    "    if (!\"variable\" %in% names(diag_k)) {\n",
    "      possible_var_cols <- c(\"variable\", \".variable\", \"parameter\", \"term\")\n",
    "      found_var <- intersect(possible_var_cols, names(diag_k))\n",
    "      if (length(found_var) > 0) {\n",
    "        names(diag_k)[names(diag_k) == found_var[1]] <- \"variable\"\n",
    "      } else {\n",
    "        diag_k$variable <- vars_k\n",
    "      }\n",
    "    }\n",
    "\n",
    "    needed_cols <- c(\"variable\", \"rhat\", \"ess_bulk\", \"ess_tail\")\n",
    "    missing_cols <- setdiff(needed_cols, names(diag_k))\n",
    "    if (length(missing_cols) > 0) {\n",
    "      for (cc in missing_cols) diag_k[[cc]] <- NA_real_\n",
    "    }\n",
    "\n",
    "    diag_list[[k]] <- diag_k[, needed_cols, drop = FALSE]\n",
    "  }\n",
    "\n",
    "  smry_diag <- do.call(rbind, diag_list)\n",
    "\n",
    "  smry <- merge(\n",
    "    smry_basic[, !names(smry_basic) %in% c(\"rhat\", \"ess_bulk\", \"ess_tail\"), drop = FALSE],\n",
    "    smry_diag[, c(\"variable\", \"rhat\", \"ess_bulk\", \"ess_tail\"), drop = FALSE],\n",
    "    by = \"variable\",\n",
    "    all.x = TRUE,\n",
    "    sort = FALSE\n",
    "  )\n",
    "\n",
    "  smry\n",
    "}\n",
    "\n",
    "make_light_mcmc_export <- function(\n",
    "    fit_obj,\n",
    "    mode,\n",
    "    harm_data = NULL,\n",
    "    modality = NULL,\n",
    "    keep_regex = \"^(gamma_base|gamma_i|mu_ig|sigma_ig|L_R_ig|nu_sigma|scale_sigma|sigma_psi|sigma_tau|sigma_delta|lp__)\",\n",
    "    max_draws = 2000,\n",
    "    include_harm_data = TRUE,\n",
    "    diag_chunk_size = 500\n",
    ") {\n",
    "  message(\"Creating lightweight MCMC diagnostic object...\")\n",
    "\n",
    "  all_vars <- tryCatch(\n",
    "    fit_obj$metadata()$stan_variables,\n",
    "    error = function(e) NULL\n",
    "  )\n",
    "\n",
    "  if (!is.null(all_vars)) {\n",
    "    keep_vars <- grep(keep_regex, all_vars, value = TRUE)\n",
    "  } else {\n",
    "    keep_vars <- NULL\n",
    "  }\n",
    "\n",
    "  if (!is.null(keep_vars) && length(keep_vars) == 0) {\n",
    "    warning(\"No variables matched keep_regex; saving no posterior_draws or mcmc_summary.\")\n",
    "    draws_df <- NULL\n",
    "  } else if (!is.null(keep_vars)) {\n",
    "    draws_df <- tryCatch(\n",
    "      as.data.frame(\n",
    "        fit_obj$draws(variables = keep_vars, format = \"draws_df\"),\n",
    "        check.names = FALSE\n",
    "      ),\n",
    "      error = function(e) {\n",
    "        warning(\"Could not extract selected posterior draws: \", e$message)\n",
    "        NULL\n",
    "      }\n",
    "    )\n",
    "  } else {\n",
    "    draws_df <- tryCatch(\n",
    "      as.data.frame(fit_obj$draws(format = \"draws_df\"), check.names = FALSE),\n",
    "      error = function(e) {\n",
    "        warning(\"Could not extract posterior draws: \", e$message)\n",
    "        NULL\n",
    "      }\n",
    "    )\n",
    "\n",
    "    if (!is.null(draws_df)) {\n",
    "      meta_cols <- intersect(c(\".chain\", \".iteration\", \".draw\"), names(draws_df))\n",
    "      param_cols <- grep(keep_regex, names(draws_df), value = TRUE)\n",
    "      draws_df <- draws_df[, unique(c(meta_cols, param_cols)), drop = FALSE]\n",
    "      keep_vars <- param_cols\n",
    "    }\n",
    "  }\n",
    "\n",
    "  draws_df <- safe_downsample_draws_by_chain(draws_df, max_draws = max_draws)\n",
    "\n",
    "  used_summary_fallback <- FALSE\n",
    "  mcmc_summary <- NULL\n",
    "\n",
    "  if (!is.null(keep_vars) && length(keep_vars) > 0) {\n",
    "    mcmc_summary <- tryCatch(\n",
    "      fit_obj$summary(variables = keep_vars),\n",
    "      error = function(e) {\n",
    "        warning(\"Could not extract selected CmdStan summary: \", e$message)\n",
    "        NULL\n",
    "      }\n",
    "    )\n",
    "  }\n",
    "\n",
    "  if (is.null(mcmc_summary) && !is.null(draws_df)) {\n",
    "    message(\"Falling back to posterior_draws-based lightweight summary.\")\n",
    "    used_summary_fallback <- TRUE\n",
    "    mcmc_summary <- summarize_draws_with_rhat_safe(\n",
    "      draws_df,\n",
    "      chunk_size = diag_chunk_size\n",
    "    )\n",
    "  }\n",
    "\n",
    "  out <- list(\n",
    "    mode = mode,\n",
    "    modality = modality,\n",
    "    export_type = \"light_mcmc_upload\",\n",
    "    mcmc_summary = mcmc_summary,\n",
    "    posterior_draws = draws_df,\n",
    "    harm_data = if (include_harm_data) harm_data else NULL,\n",
    "    created_at = Sys.time(),\n",
    "    light_export_settings = list(\n",
    "      keep_regex = keep_regex,\n",
    "      max_draws = max_draws,\n",
    "      include_harm_data = include_harm_data,\n",
    "      diag_chunk_size = diag_chunk_size,\n",
    "      summary_fallback = used_summary_fallback\n",
    "    ),\n",
    "    note = paste(\n",
    "      \"Lightweight upload object for HarmonizeR.\",\n",
    "      \"Full CmdStan fit, stan_result, and full_result are intentionally excluded.\",\n",
    "      \"If CmdStan summary extraction failed, mcmc_summary was reconstructed from selected posterior_draws.\"\n",
    "    )\n",
    "  )\n",
    "\n",
    "  out\n",
    "}\n"
  )
}

#' Build a standalone MCMC harmonization script
#'
#' Generates the self-contained R script downloaded from the Shiny app.
#' The generated script runs Stan harmonization, writes harmonized CSVs,
#' saves full local results, and creates lightweight upload files with
#' safe posterior-draw summaries.
#'
#' @param m Number of modalities/metrics.
#' @param G Number of features.
#' @param n Number of observations.
#' @param batch_levels Character vector of batch levels.
#' @param feat_names Feature names.
#' @param harm_mode Either `"uni"` or `"multi"`.
#' @param formula_txt Model formula as text.
#' @param ref_batch Optional reference batch.
#' @param is_longitudinal Logical; whether data are longitudinal.
#' @param random_var Optional subject/random-effect variable for longitudinal lmer models.
#' @param visit_col Optional visit column name.
#' @param model_type Regression model type: `"lm"`, `"gam"`, or `"lmer"`.
#' @param harm_eb Logical; use empirical Bayes shrinkage.
#' @param harm_robust Logical; use robust least-squares scale.
#' @param harm_cov Logical; run CovBat adjustment.
#' @param harm_vt Variance threshold for CovBat.
#' @param harm_minr Minimum number of PCs for CovBat.
#' @param harm_maxr Maximum number of PCs for CovBat.
#' @param harm_robcov Logical; use robust covariance target.
#' @param chains Number of MCMC chains.
#' @param parallel_chains Number of parallel chains.
#' @param adapt_delta Stan adapt_delta.
#' @return Character string containing the generated script.
#' @export
# =============================================================================
build_mcmc_script <- function(
    m, G, n, batch_levels, feat_names,
    harm_mode,           # "uni" | "multi"
    formula_txt,         # e.g. "y ~ age + sex"
    ref_batch,           # NULL or character
    is_longitudinal,
    random_var,          # NULL or e.g. "subid"
    visit_col,
    model_type,          # "lm" | "gam" | "lmer"
    harm_eb,
    harm_robust,
    harm_cov,
    harm_vt,
    harm_minr,
    harm_maxr,
    harm_robcov,
    chains,
    parallel_chains,
    adapt_delta
) {
  
  ref_str   <- if (is.null(ref_batch) || ref_batch == "") "NULL"
  else paste0('"', ref_batch, '"')
  model_str <- switch(model_type,
                      "lm"   = "stats::lm",
                      "gam"  = "mgcv::gam",
                      "lmer" = "lme4::lmer",
                      "stats::lm")
  formula_str <- if (!is.null(formula_txt) && nchar(trimws(formula_txt)) > 0)
    paste0('as.formula("', trimws(formula_txt), '")')
  else "NULL"
  mode_comment <- if (harm_mode == "multi") "Multivariate (joint across modalities)"
  else "Univariate (per modality separately)"
  
  lmer_note <- if (is_longitudinal && model_type == "lmer" && !is.null(random_var))
    paste0('\n# NOTE: longitudinal data - random effect (',
           random_var,
           ') appended to formula automatically below\n')
  else ""
  
  formula_build <- if (is_longitudinal && model_type == "lmer" && !is.null(random_var)) {
    paste0(
      'base_formula <- ', formula_str, '\n',
      'if (!is.null(base_formula)) {\n',
      '  f_str <- paste(deparse(base_formula), collapse = "")\n',
      '  if (!grepl("\\\\|", f_str)) {\n',
      '    formula_use <- as.formula(paste(f_str, "+ (1 | ', random_var, ')"))\n',
      '  } else { formula_use <- base_formula }\n',
      '} else {\n',
      '  formula_use <- as.formula("y ~ 1 + (1 | ', random_var, ')")\n',
      '}\n'
    )
  } else {
    paste0('formula_use <- ', formula_str, '\n')
  }
  
  harm_call <- if (harm_mode == "uni") {
    paste0(
      '# --- Run univariate Stan ComBat for each modality ---\n',
      'results <- vector("list", m)\n',
      'for (i in seq_len(m)) {\n',
      '  message("\\n=== Modality ", i, " of ", m, " ===")\n',
      '  results[[i]] <- com_harm(\n',
      '    bat        = bat_list[[i]],\n',
      '    data       = data_list[[i]],\n',
      '    covar      = covar_list[[i]],\n',
      '    model      = ', model_str, ',\n',
      '    formula    = formula_use,\n',
      '    ref.batch  = ref_batch,\n',
      '    eb         = ', toupper(harm_eb), ',\n',
      '    stan       = TRUE,\n',
      '    robust.LS  = ', toupper(harm_robust), ',\n',
      '    cov        = ', toupper(harm_cov), ',\n',
      if (harm_cov) paste0(
        '    var_thresh = ', harm_vt, ',\n',
        '    min_rblock = ', harm_minr, ',\n',
        '    max_rblock = ', harm_maxr, ',\n'
      ) else '',
      '    stan_control = list(\n',
      '      chains = chains,\n',
      '      parallel_chains = parallel_chains,\n',
      '      adapt_delta = adapt_delta\n',
      '    )\n',
      '  )\n',
      '}\n',
      '\n',
      '# Collect harmonized data and Stan fit objects\n',
      'harm_data   <- lapply(results, `[[`, "harm_data")\n',
      'stan_result <- lapply(results, `[[`, "stan_result")\n'
    )
  } else {
    paste0(
      '# --- Run multivariate Stan ComBat (joint across modalities) ---\n',
      'res <- com_harm.multivariate(\n',
      '  bat             = bat_list,\n',
      '  data            = data_list,\n',
      '  covar           = covar_list,\n',
      '  model           = ', model_str, ',\n',
      '  formula         = formula_use,\n',
      '  ref.batch       = ref_batch,\n',
      '  eb              = ', toupper(harm_eb), ',\n',
      '  stan            = TRUE,\n',
      '  robust.LS       = ', toupper(harm_robust), ',\n',
      '  cov             = ', toupper(harm_cov), ',\n',
      if (harm_cov) paste0(
        '  var_thresh      = ', harm_vt, ',\n',
        '  min_rblock      = ', harm_minr, ',\n',
        '  max_rblock      = ', harm_maxr, ',\n'
      ) else '',
      '  robust_cov      = ', toupper(harm_robcov), ',\n',
      '  stan_control    = list(\n',
      '    chains = chains,\n',
      '    parallel_chains = parallel_chains,\n',
      '    adapt_delta = adapt_delta\n',
      '  )\n',
      ')\n',
      '\n',
      'harm_data   <- res$harm_data\n',
      'stan_result <- res$stan_result\n'
    )
  }
  
  light_export_helper <- mcmc_light_export_helper_code()

  paste0(
    '# =============================================================================\n',
    '# HarmonizeR - MCMC (Stan) Harmonization Script\n',
    '# Generated by HarmonizeR Shiny App\n',
    '# Generated at: ', format(Sys.time(), "%Y-%m-%d %H:%M:%S"), '\n',
    '# =============================================================================\n',
    '#\n',
    '# Mode        : ', mode_comment, '\n',
    '# Modalities  : m = ', m, '\n',
    '# Obs/samples : n = ', n, '\n',
    '# Features    : G = ', G, '\n',
    '# Batches     : ', paste(batch_levels, collapse = ", "), '\n',
    '# Data type   : ', if (is_longitudinal) "Longitudinal" else "Cross-sectional", '\n',
    '#\n',
    '# HOW TO RUN\n',
    '# ----------\n',
    '# 1. Unzip the downloaded HarmonizeR MCMC project folder.\n',
    '# 2. Install cmdstanr if not already installed:\n',
    '#    install.packages("cmdstanr",\n',
    '#      repos = c("https://mc-stan.org/r-packages/", getOption("repos")))\n',
    '#    cmdstanr::install_cmdstan()\n',
    '# 3. Install/load MultiComBat as needed.\n',
    '# 4. Open R/RStudio and set the working directory to the project root.\n',
    '# 5. Run: source("R/run_mcmc_harmonization.R")\n',
    '#\n',
    '# INPUT\n',
    '# -----\n',
    '# data/ contains modality CSVs, batch labels, and covariates exported by Shiny.\n',
    '#\n',
    '# OUTPUT\n',
    '# ------\n',
    '# harm_data        : list of m harmonized data frames\n',
    '# stan_result      : Stan fit object(s) used for Bayesian diagnostics\n',
    '# Harmonized CSVs  : written to results/harmonized/\n',
    '# Stan RDS         : *_FULL_LOCAL.rds for local reproducibility; *_LIGHT_UPLOAD.rds for Shiny upload\n',
    '# =============================================================================\n\n',
    
    '# -- 1. Packages ---------------------------------------------------------------\n',
    'suppressPackageStartupMessages({\n',
    '  library(MultiComBat)\n',
    '  library(cmdstanr)   # MCMC backend\n',
    '  library(posterior)  # lightweight R-hat / ESS summaries\n',
    '  library(dplyr)\n',
    if (model_type == "gam")  '  library(mgcv)\n'  else '',
    if (model_type == "lmer") '  library(lme4)\n'  else '',
    '})\n\n',
    
    light_export_helper,
    
    '# -- 2. MCMC settings (tune as needed) ----------------------------------------\n',
    'chains          <- ', chains, 'L\n',
    'parallel_chains <- ', parallel_chains, 'L\n',
    'adapt_delta     <- ', adapt_delta, '\n\n',
    
    '# -- 3. Harmonization settings -------------------------------------------------\n',
    'ref_batch <- ', ref_str, '\n\n',
    
    '# -- 4. Formula ----------------------------------------------------------------\n',
    lmer_note,
    formula_build, '\n',
    
    '# -- 5. LOAD YOUR DATA ---------------------------------------------------------\n',
    '# The downloaded project folder already contains all required inputs under data/.\n',
    '# Expected structure:\n',
    '#   data_list  : list of m data frames, each n x G, identical column names\n',
    '#   bat_list   : list of m factor vectors of length n (batch labels)\n',
    '#   covar_list : list of m data frames (covariates), or list of NULLs\n',
    '#\n',
    'message("Loading data from data/ ...")\n',
    'm <- ', m, 'L\n',
    'data_list <- lapply(seq_len(m), function(i) {\n',
    '  read.csv(file.path("data", paste0("modality_", i, ".csv")),\n',
    '           row.names = 1, check.names = FALSE)\n',
    '})\n',
    'bat_raw <- read.csv(file.path("data", "batch_labels.csv"),\n',
    '                    check.names = FALSE)[[1]]\n',
    'bat_list <- replicate(m, factor(bat_raw), simplify = FALSE)\n',
    'covar_raw <- read.csv(file.path("data", "covariates.csv"),\n',
    '                      check.names = FALSE)\n',
    'covar_list <- replicate(m, covar_raw, simplify = FALSE)\n\n',
    
    '# -- 6. Run Stan harmonization -------------------------------------------------\n',
    'message("Starting Stan MCMC harmonization - this may take several minutes to hours")\n',
    'message("  Chains: ', chains, '  |  Parallel: ', parallel_chains,
    '  |  adapt_delta: ', adapt_delta, '")\n',
    'message("  Mode: ', mode_comment, '")\n\n',
    harm_call, '\n',
    
    '# -- 7. Save outputs ----------------------------------------------------------\n',
    'message("Saving harmonized data and Stan outputs...")\n',
    'dir.create("results", showWarnings = FALSE)\n',
    'dir.create(file.path("results", "harmonized"), showWarnings = FALSE, recursive = TRUE)\n',
    'dir.create(file.path("results", "stan_fits"),  showWarnings = FALSE, recursive = TRUE)\n\n',
    'for (i in seq_len(m)) {\n',
    '  out_i <- as.data.frame(harm_data[[i]], check.names = FALSE)\n',
    '  out_i$.__row_id__ <- rownames(out_i)\n',
    '  out_i <- out_i[, c(".__row_id__", setdiff(names(out_i), ".__row_id__")), drop = FALSE]\n',
    '  write.csv(out_i,\n',
    '            file = file.path("results", "harmonized", paste0("harm_data_M", i, ".csv")),\n',
    '            row.names = FALSE)\n',
    '}\n',
    'message("  Harmonized CSVs written to results/harmonized/ with an explicit .__row_id__ column")\n\n',
    if (harm_mode == "uni") {
      paste0(
        '# Save univariate outputs: one FULL_LOCAL and one LIGHT_UPLOAD file per modality.\n',
        'for (i in seq_len(m)) {\n',
        '  fit_i <- stan_result[[i]]$fit\n',
        '\n',
        '  mcmc_summary_i <- tryCatch(\n',
        '    fit_i$summary(),\n',
        '    error = function(e) {\n',
        '      warning("Could not extract MCMC summary for modality ", i, ": ", e$message)\n',
        '      NULL\n',
        '    }\n',
        '  )\n',
        '\n',
        '  full_export_i <- list(\n',
        '    mode = "univariate",\n',
        '    modality = i,\n',
        '    export_type = "full_local",\n',
        '    harm_data = harm_data[[i]],\n',
        '    stan_result = stan_result[[i]],\n',
        '    full_result = results[[i]],\n',
        '    mcmc_summary = mcmc_summary_i,\n',
        '    created_at = Sys.time(),\n',
        '    note = "Full local object. Keep for reproducibility; not recommended for Shiny upload."\n',
        '  )\n',
        '\n',
        '  saveRDS(\n',
        '    full_export_i,\n',
        '    file = file.path("results", "stan_fits", paste0("stan_result_M", i, "_FULL_LOCAL.rds")),\n',
        '    compress = FALSE\n',
        '  )\n',
        '\n',
        '  light_export_i <- make_light_mcmc_export(\n',
        '    fit_obj = fit_i,\n',
        '    mode = "univariate",\n',
        '    modality = i,\n',
        '    harm_data = harm_data[[i]],\n',
        '    keep_regex = "^(gamma_i|mu_ig|sigma_psi|sigma_tau|sigma_delta|lp__)",\n',
        '    max_draws = 2000,\n',
        '    include_harm_data = TRUE\n',
        '  )\n',
        '\n',
        '  saveRDS(\n',
        '    light_export_i,\n',
        '    file = file.path("results", "stan_fits", paste0("stan_result_M", i, "_LIGHT_UPLOAD.rds")),\n',
        '    compress = "xz"\n',
        '  )\n',
        '}\n',
        '\n',
        'message("  Full local files written as:  stan_result_M*_FULL_LOCAL.rds")\n',
        'message("  Upload files written as:      stan_result_M*_LIGHT_UPLOAD.rds")\n',
        'message("  For HarmonizeR upload, use only the *_LIGHT_UPLOAD.rds files.")\n'
      )
    } else {
      paste0(
        'fit_obj <- stan_result$fit\n',
        '\n',
        'mcmc_summary <- tryCatch(\n',
        '  fit_obj$summary(),\n',
        '  error = function(e) {\n',
        '    warning("Could not extract MCMC summary: ", e$message)\n',
        '    NULL\n',
        '  }\n',
        ')\n',
        '\n',
        'full_export <- list(\n',
        '  mode = "multivariate",\n',
        '  export_type = "full_local",\n',
        '  harm_data = harm_data,\n',
        '  stan_result = stan_result,\n',
        '  full_result = res,\n',
        '  mcmc_summary = mcmc_summary,\n',
        '  created_at = Sys.time(),\n',
        '  note = "Full local object. Keep for reproducibility; not recommended for Shiny upload."\n',
        ')\n',
        '\n',
        'saveRDS(\n',
        '  full_export,\n',
        '  file = file.path("results", "stan_fits", "stan_result_multivariate_FULL_LOCAL.rds"),\n',
        '  compress = FALSE\n',
        ')\n',
        '\n',
        'light_export <- make_light_mcmc_export(\n',
        '  fit_obj = fit_obj,\n',
        '  mode = "multivariate",\n',
        '  modality = NULL,\n',
        '  harm_data = harm_data,\n',
        '  keep_regex = "^(gamma_base|mu_ig|sigma_ig|L_R_ig|nu_sigma|scale_sigma|lp__)",\n',
        '  max_draws = 2000,\n',
        '  include_harm_data = TRUE\n',
        ')\n',
        '\n',
        'saveRDS(\n',
        '  light_export,\n',
        '  file = file.path("results", "stan_fits", "stan_result_multivariate_LIGHT_UPLOAD.rds"),\n',
        '  compress = "xz"\n',
        ')\n',
        '\n',
        'message("  Full local file written as:  stan_result_multivariate_FULL_LOCAL.rds")\n',
        'message("  Upload file written as:      stan_result_multivariate_LIGHT_UPLOAD.rds")\n',
        'message("  For HarmonizeR upload, use only stan_result_multivariate_LIGHT_UPLOAD.rds.")\n'
      )
    }, '\n',
    
    '# -- 8. Quick MCMC diagnostics -------------------------------------------------\n',
    '# Avoid full fit_obj$summary() here because it can exceed memory for large models.\n',
    '# Instead, use the lightweight upload summaries that were already created above.\n',
    'message("\\nRunning quick MCMC diagnostics from LIGHT_UPLOAD summaries...")\n',
    if (harm_mode == "uni") {
      paste0(
        "for (i in seq_len(m)) {\n",
        "  light_file_i <- file.path(\"results\", \"stan_fits\", paste0(\"stan_result_M\", i, \"_LIGHT_UPLOAD.rds\"))\n",
        "  if (file.exists(light_file_i)) {\n",
        "    light_i <- readRDS(light_file_i)\n",
        "    smry <- light_i$mcmc_summary\n",
        "    message(\"\\n--- Modality \", i, \" ---\")\n",
        "    if (!is.null(smry) && all(c(\"rhat\", \"ess_bulk\") %in% names(smry))) {\n",
        "      rhat_bad <- smry[!is.na(smry$rhat) & smry$rhat > 1.05, , drop = FALSE]\n",
        "      ess_bad  <- smry[!is.na(smry$ess_bulk) & smry$ess_bulk < 400, , drop = FALSE]\n",
        "      message(\"  R-hat > 1.05  : \", nrow(rhat_bad), \" saved parameters\")\n",
        "      message(\"  ESS_bulk < 400: \", nrow(ess_bad),  \" saved parameters\")\n",
        "      if (nrow(rhat_bad) > 0 && \"variable\" %in% names(rhat_bad)) {\n",
        "        message(\"  Worst R-hat saved parameters:\")\n",
        "        print(head(rhat_bad[order(-rhat_bad$rhat), c(\"variable\", \"rhat\"), drop = FALSE], 5))\n",
        "      }\n",
        "    } else {\n",
        "      message(\"  No usable lightweight R-hat/ESS summary available.\")\n",
        "    }\n",
        "  }\n",
        "}\n"
      )
    } else {
      paste0(
        "light_file <- file.path(\"results\", \"stan_fits\", \"stan_result_multivariate_LIGHT_UPLOAD.rds\")\n",
        "if (file.exists(light_file)) {\n",
        "  light_obj <- readRDS(light_file)\n",
        "  smry <- light_obj$mcmc_summary\n",
        "  if (!is.null(smry) && all(c(\"rhat\", \"ess_bulk\") %in% names(smry))) {\n",
        "    rhat_bad <- smry[!is.na(smry$rhat) & smry$rhat > 1.05, , drop = FALSE]\n",
        "    ess_bad  <- smry[!is.na(smry$ess_bulk) & smry$ess_bulk < 400, , drop = FALSE]\n",
        "    message(\"  R-hat > 1.05  : \", nrow(rhat_bad), \" saved parameters\")\n",
        "    message(\"  ESS_bulk < 400: \", nrow(ess_bad),  \" saved parameters\")\n",
        "    if (nrow(rhat_bad) > 0 && \"variable\" %in% names(rhat_bad)) {\n",
        "      message(\"  Worst R-hat saved parameters:\")\n",
        "      print(head(rhat_bad[order(-rhat_bad$rhat), c(\"variable\", \"rhat\"), drop = FALSE], 5))\n",
        "    }\n",
        "  } else {\n",
        "    message(\"  No usable lightweight R-hat/ESS summary available.\")\n",
        "  }\n",
        "}\n"
      )
    }, '\n',
    'message("\\nDone! Upload the *_LIGHT_UPLOAD.rds file(s) in ./results/stan_fits/ to HarmonizeR.")\n'
  )
}

